version: '3'

services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/alunir/app
    env_file:
      - alunir/main/resources/common.env
      - alunir/main/resources/bband_strategy.env
    working_dir: /home
    entrypoint: python alunir/main/strategy/bitmex/bband_strategy.py
