version: '3'
services:
  app:
    logging:
      driver: awslogs
      options:
        awslogs-group: alunir
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: alunir
    entrypoint: python REAL=True alunir/main/strategy/bitmex/bband_strategy.py
