#!/bin/bash
# MEMO: Right one will override the left one
export $(grep -h AWS_ ./alunir/main/resources/*.env | xargs)
# MEMO: if you use bazel test with env. variables, set the following line.
echo "Successfully set environment variables."

aws configure set aws_access_key_id ${AWS_ACCOUNT_ID}
aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
aws configure set region ${AWS_DEFAULT_REGION}
`aws ecr get-login --no-include-email --region ap-northeast-1`

if [ $1 = test ]; then
    export STRATEGY_NAME=test
    docker-compose --file docker-compose.yml --file docker-compose.local.yml up test
else
    export STRATEGY_NAME=$1
    export $(cat alunir/main/resources/${STRATEGY_NAME}.env | xargs)
    docker-compose --file docker-compose.yml --file docker-compose.local.yml pull app
    docker-compose --file docker-compose.yml --file docker-compose.local.yml up app
fi
